import type { Metadata } from "next";
import localFont from "next/font/local";
import { AuthProvider } from "@/contexts/AuthContext";
import { ToastProvider } from "@/components/ToastProvider";
import "./globals.css";
import { Providers } from '@/store/provider';
import { Chat } from '@/components/Chat/Chat';
import NavbarWrapper from '@/components/NavbarWrapper';

const geistSans = localFont({
  src: '../fonts/geistMono-regular.otf',
  variable: "--font-geist-sans",
});

const geistMono = localFont({
  src: '../fonts/geistMonoVF.ttf',
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <AuthProvider>
            <NavbarWrapper />
            {children}
            <ToastProvider />
            <Chat />
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
