import type { Metadata } from "next";
import { AuthProvider } from "@/contexts/AuthContext";
import { ToastProvider } from "@/components/ToastProvider";
import "./globals.css";
import { Providers } from '@/store/provider';
import { Chat } from '@/components/Chat/Chat';
import NavbarWrapper from '@/components/NavbarWrapper';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Use Tailwind's `font-sans` to apply system fonts */}
      <body className="font-sans antialiased">
        <Providers>
          <AuthProvider>
            <NavbarWrapper />
            {children}
            <ToastProvider />
            <Chat />
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
